version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: api-survey-mariadb
    ports:
      - '3307:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - api-survey:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: api-survey-phpmyadmin
    depends_on:
      - database
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DB_USER_NAME}
      PMA_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - api-survey:/var/lib/phpmyadmin

volumes:
  api-survey:
    name: api-survey